[package]
name = "warmup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
hex = "0.4.3"
log = "0.4.21"
ring = "0.17.8"
serde = "1.0.197"
